### ISSUE TITLE
Add uv (Python package manager) to .chezmoidata.yaml package list

### ISSUE THREAD

**Issue by entelecheia** [entelecheia/dotfiles#152]
## Description

We should add `uv`, an extremely fast Python package and project manager written in Rust, to our `.chezmoidata.yaml` package list.

## Proposed Changes

Add the following entry to the `packages` list in `.chezmoidata.yaml`:

```yaml
- name: uv
  script: true
  script_cmd: "curl -LsSf https://astral.sh/uv/install.sh | sh"
  check_installed: "command -v uv &> /dev/null"
  current_version: "uv --version | cut -d' ' -f2"
  latest_version: $(curl -s https://api.github.com/repos/astral-sh/uv/releases/latest | grep 'tag_name' | cut -d'"' -f4)
  scope: optional
  allow_upgrade: true
```

Additional Information

- Installation method: Using the standalone installer script
- Self-update feature: uv self update
- Official website: https://github.com/astral-sh/uv
  Checklist
- Update .chezmoidata.yaml
- Test installation on a fresh system
- Update documentation if necessary
