### ISSUE TITLE
Modify lfs-folderstore-init task@Taskfile.dist.yaml.tmpl

### ISSUE THREAD

**Issue by entelecheia** [entelecheia/dotfiles#67]
After cloning the repository, lfs-folderstore-init task initializes the LFS folderstore.  The task is defined in the Taskfile.dist.yaml.tmpl file.  The task is defined as follows:

```yaml
  lfs-folderstore-init:
    desc: Initialize the LFS folderstore for the current Git repository
    dir: {{"'{{.USER_WORKING_DIR}}'"}}
    cmds:
      - git config --add lfs.customtransfer.lfs-folder.path "${HOME}/.local/bin/lfs-folderstore"
      - git config --add lfs.customtransfer.lfs-folder.args "{{ .lfs_folderstore.store_dir }}"
      - git config --add lfs.standalonetransferagent lfs-folder
      - git config lfs.url "https://localhost"
```

After this, you need to run `git reset --hard main` to apply the changes. Consider adding this command to the task or specify it in the task description.

Refer to the [Git LFS: Shared Folder agent](https://github.com/sinbad/lfs-folderstore) repository for more information about the lfs-folderstore tool.
